# Generated by Django 2.1 on 2020-03-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwardrank', '0002_comments_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='github_repo',
            new_name='project_link',
        ),
    ]
